#!/bin/bash

echo "=========================================="
echo "SUPABASE MIGRATION - QUICK STEPS"
echo "=========================================="
echo ""
echo "Since database password is needed, please use the Supabase Dashboard:"
echo ""
echo "1. Open this link in your browser:"
echo "   https://supabase.com/dashboard/project/qalcyeaxuivvgqukrpzt/sql"
echo ""
echo "2. Copy ALL contents from this file:"
echo "   supabase/migrations/20250122_initial_schema.sql"
echo ""
echo "3. Paste into the SQL Editor and click 'Run'"
echo ""
echo "4. Verify success by checking the Table Editor:"
echo "   https://supabase.com/dashboard/project/qalcyeaxuivvgqukrpzt/editor"
echo ""
echo "=========================================="
echo ""
echo "Alternatively, if you have the database password:"
echo ""
echo "1. Get password from: Settings → Database"
echo "2. Run: supabase db push"
echo "3. Enter the password when prompted"
echo ""
echo "=========================================="